info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T01:49:02.226Z"}
info: Connected to the database. {"timestamp":"2022-05-20T01:49:02.249Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:49:52.768Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:50:04.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T01:50:52.271Z"}
info: Connected to the database. {"timestamp":"2022-05-20T01:50:52.289Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:51:57.899Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T02:31:20.216Z"}
info: Connected to the database. {"timestamp":"2022-05-20T02:31:20.238Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T03:12:02.363Z"}
info: Connected to the database. {"timestamp":"2022-05-20T03:12:02.386Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T03:12:33.935Z"}
info: Connected to the database. {"timestamp":"2022-05-20T03:12:33.966Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:04:56.036Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:04:56.068Z"}
error: 
    status - 500 
    message - TypeError: UserService.newUser is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userRegistration (D:\projectt\fundo-notes\src\controllers\/user.controller.js:28:31)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at userRegistrationValidator (D:\projectt\fundo-notes\src\validators\/user.validator.js:15:5)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:06:24.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:06:42.226Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:06:42.258Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:11:30.051Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:11:30.084Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:20.101Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:20.129Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:25.881Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:25.916Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:37.332Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:37.375Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:44.553Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:44.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:54.266Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:54.336Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "abcde@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-20T04:13:05.785Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:13:05.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:03.687Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:03.744Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:17.567Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:17.614Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:22.085Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:22.118Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:26.552Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:26.585Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:16:53.006Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:16:53.037Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:04.990Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:05.023Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:28.613Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:28.649Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:48.131Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:48.171Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:19:05.272Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:19:05.302Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:20:04.078Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:20:04.119Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:00.557Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:00.594Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:13.219Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:13.252Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:21.234Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:21.272Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:22:55.979Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:22:56.003Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:29.408Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:29.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:33.255Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:33.293Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:42.713Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:42.750Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:25:35.901Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:25:35.930Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:25:40.467Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:25:40.497Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:29:45.059Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:29:45.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:29:58.858Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:29:58.889Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:30:17.066Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:30:17.107Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:30:26.235Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:30:26.270Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:31:45.265Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:31:45.299Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:31:52.597Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:31:52.626Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:05.949Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:05.982Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:11.475Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:11.508Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:51.150Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:51.185Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:33:10.335Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:33:10.364Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:33:16.771Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:33:16.804Z"}
error: 
    status - 500 
    message - ReferenceError: saltRound is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:29:38)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.newUser (D:\projectt\fundo-notes\src\services\/user.service.js:16:21)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:33:58.944Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:34:34.739Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:34:34.765Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:34:54.992Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:34:55.017Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:36:00.179Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:36:00.208Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:40.420Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:40.447Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:46.368Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:46.394Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:49.172Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:49.202Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:56.982Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:57.009Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:39:36.262Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:39:36.287Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:40:54.499Z"}
error: 
    status - 500 
    message - ValidationError: "email" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:41:09.883Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:43)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:41:22.501Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:14.882Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:14.907Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:17.241Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:17.262Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:58.985Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:59.007Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:31.494Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:31.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:35.898Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:35.923Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:52.658Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:52.681Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:12.824Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:12.854Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:24.350Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:24.374Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:29.365Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:29.386Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:28.942Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:28.977Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:35.364Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:35.402Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:38.002Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:38.029Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:44.369Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:44.389Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:54.844Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:54.869Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:46:05.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:47:23.353Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:47:23.380Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:47:27.388Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:47:56.444Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:47:56.475Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:48:00.524Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:48:49.800Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:48:49.824Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:48:53.533Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:48:53.564Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:48:57.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:50:45.121Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:50:45.153Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:12.430Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:12.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:26.502Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:26.527Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:34.065Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:34.091Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:51:51.780Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:51:53.304Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:52:45.822Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:52:45.845Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:53:40.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:11.769Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:11.793Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:54:18.852Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:27.378Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:27.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:40.249Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:40.274Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:48.783Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:48.814Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:58.469Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:58.504Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T08:58:09.509Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:07:33.711Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:07:33.748Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:07:39.048Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:07:39.076Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:04.752Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:04.776Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:23.289Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:23.318Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:34.105Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:34.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:40.207Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:40.233Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:11:05.404Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:11:05.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:03:35.719Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:03:35.751Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:03:46.917Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:03:46.948Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:09:41.540Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:09:41.565Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:43)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:09:58.724Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:15.758Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:15.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:20.974Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:21.005Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:27.492Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:27.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:34.207Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:34.232Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:10:51.579Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:16:25.691Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:16:25.722Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:16:48.979Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:16:49.012Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got barbade123@gmail.com
    at model.Query.Query.findOne (D:\projectt\fundo-notes\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (D:\projectt\fundo-notes\node_modules\mongoose\lib\model.js:2267:13)
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:27)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:18:50.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:19:17.099Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:19:17.132Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:19:23.838Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:28:26.631Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:28:26.664Z"}
